name = "personal-website-2"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Development database (local)
[[d1_databases]]
binding = "DB"
database_name = "website-analytics-dev"
database_id = "1b1e0384-e617-4b2d-b8a4-4baf966c9148"
preview_database_id = "1b1e0384-e617-4b2d-b8a4-4baf966c9148"

# Production environments
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "website-analytics"
database_id = "000d5a9f-9a87-474d-8a74-11d300d2581f"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "website-analytics"
database_id = "000d5a9f-9a87-474d-8a74-11d300d2581f"
