name = "personal-website-2"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Preview environment (used for development and preview deployments)
[[d1_databases]]
binding = "DB"
database_name = "analytics-db"
database_id = "e9ae067f-d6af-48e5-8349-3c0899145d36"
migrations_dir = "migrations"


[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_id = "e9ae067f-d6af-48e5-8349-3c0899145d36"
migrations_dir = "migrations"

# Production environment
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "analytics-db"
database_id = "e9ae067f-d6af-48e5-8349-3c0899145d36"
migrations_dir = "migrations"


[ai]
binding = "AI"