name = "personal-website-2"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Preview environment (used for development and preview deployments)
[[d1_databases]]
binding = "DB"
database_name = "analytics-db"
database_id = "a6a0b776-e0da-40f7-b955-c966bf2ac02e"

[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "analytics-db"
database_id = "a6a0b776-e0da-40f7-b955-c966bf2ac02e"

# Production environment
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "analytics-db"
database_id = "a6a0b776-e0da-40f7-b955-c966bf2ac02e"
migrations_dir = "migrations"
