name: Deployment Metrics

on:
  push:
    branches:
      - main

jobs:
  track-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm add -D typescript @types/jest @types/node jest ts-jest @jest/globals
          pnpm add -g wrangler
          
      - name: Run Tests
        run: |
          # Run tests with ts-jest
          pnpm jest --config jest.config.js
          
      - name: Build TypeScript
        run: |
          # Compile scripts using the dedicated config
          pnpm tsc -p tsconfig.scripts.json
          
          # Add execute permission to the CLI script
          chmod +x dist/scripts/collect-metrics-cli.js
      - name: Check Wrangler WhoAMI
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          wrangler whoami
          
      - name: Collect and Save Metrics
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          DEPLOY_TIME=$(date +%s)
          BUILD_TIME=$(date +%s)
          
          node dist/scripts/collect-metrics-cli.js \
            $DEPLOY_TIME \
            $BUILD_TIME \
            "success" \
            "production" \
            "${{ github.sha }}" \
            "${{ github.ref }}" 